### ISSUE TITLE
Design the Database Schema

### ISSUE THREAD

**Issue by mehalyna** [Project-Stage-Academy/ChNU-Practics-2024#1]
**Objective**: To create a well-structured database schema that efficiently supports the application's data requirements.

**Sub-Tasks**:
1. **Identify Entities and Relationships**:
   - Analyze the project requirements to identify key entities such as startups, investors, profiles, projects, messages, etc.
   - Determine the relationships between these entities (one-to-many, many-to-many, etc.).

2. **Define Entity Attributes**:
   - List down the attributes for each entity, like startup name, investor details, project descriptions, contact information, etc.

3. **Create ER Diagrams**:
   - Use a database modeling tool to create Entity-Relationship (ER) diagrams representing the structure of the database.

4. **Normalize Database**:
   - Ensure the database design adheres to normalization rules to reduce redundancy and improve data integrity.

5. **Review and Iterate**:
   - Review the schema with the team and iterate based on feedback.

**Comment by Adeliona** [comment]
https://dbdiagram.io/d/db-chnu-65c10a10ac844320ae7cccbc

**Comment by ivtkac** [comment]
<picture>
    <source srcset="https://github.com/Project-Stage-Academy/ChNU-Practics-2024/assets/116971836/4f4ebcc1-4865-4dda-acd4-c753cf980c71" media="(prefers-color-scheme: dark)">
    <img src="https://github.com/Project-Stage-Academy/ChNU-Practics-2024/assets/116971836/2f9d661c-0605-4fc4-9781-c22c99f97e5f">
</picture>
